import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getDoctorAppointments, toLocalDate, type DoctorAppointment } from '../services/doctor/workspaceService';
import { appointmentStatusLabels, statusBadgeClass } from '../types/appointmentStatus';

const DoctorCalendarPage = () => {
  const [anchor, setAnchor] = useState(new Date());
  const [view, setView] = useState<'day' | 'week'>('day');
  const [items, setItems] = useState<DoctorAppointment[]>([]);
  const [loading, setLoading] = useState(true);
  const range = useMemo(() => { const start = new Date(anchor); if (view === 'week') start.setDate(anchor.getDate() - ((anchor.getDay() + 6) % 7)); const end = new Date(start); end.setDate(start.getDate() + (view === 'week' ? 6 : 0)); return { start, end }; }, [anchor, view]);
  useEffect(() => { setLoading(true); void getDoctorAppointments(toLocalDate(range.start), toLocalDate(range.end)).then(setItems).catch(console.error).finally(() => setLoading(false)); }, [range]);
  const days = Array.from({ length: view === 'week' ? 7 : 1 }, (_, index) => { const date = new Date(range.start); date.setDate(date.getDate() + index); return date; });
  const move = (direction: number) => { const next = new Date(anchor); next.setDate(next.getDate() + direction * (view === 'week' ? 7 : 1)); setAnchor(next); };
  return <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-cyan-700 dark:text-cyan-300">Takvim</p><h1 className="text-3xl font-bold text-slate-950 dark:text-white">Klinik program</h1></div><div className="flex rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-slate-950">{(['day','week'] as const).map((mode) => <button key={mode} onClick={() => setView(mode)} className={`rounded-lg px-4 py-2 text-sm ${view === mode ? 'bg-cyan-600 text-white' : 'text-slate-600 dark:text-slate-300'}`}>{mode === 'day' ? 'Gün' : 'Hafta'}</button>)}</div></header><div className="mt-6 flex items-center gap-2"><button onClick={() => move(-1)} aria-label="Önceki dönem" className="rounded-lg border p-2 dark:border-slate-700"><ChevronLeft /></button><button onClick={() => setAnchor(new Date())} className="rounded-lg border px-4 py-2 text-sm dark:border-slate-700">Bugün</button><button onClick={() => move(1)} aria-label="Sonraki dönem" className="rounded-lg border p-2 dark:border-slate-700"><ChevronRight /></button><span className="ml-2 text-sm text-slate-500">{range.start.toLocaleDateString('tr-TR')} – {range.end.toLocaleDateString('tr-TR')}</span></div><section className={`mt-6 grid gap-3 ${view === 'week' ? 'lg:grid-cols-7' : ''}`}>{days.map((day) => { const date = toLocalDate(day); const dayItems = items.filter((item) => item.appointment_date === date); return <article key={date} className="min-h-48 rounded-2xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-950"><h2 className="border-b border-slate-200 pb-3 text-sm font-semibold dark:border-slate-800">{day.toLocaleDateString('tr-TR', { weekday: 'short', day: 'numeric', month: 'short' })}</h2><div className="mt-3 space-y-2">{loading && <p className="text-xs text-slate-500">Yükleniyor...</p>}{dayItems.map((item) => <Link key={item.appointment_id} to={`/doctor/appointment/${item.appointment_id}`} className="block rounded-xl border border-slate-200 p-3 hover:border-cyan-400 dark:border-slate-700"><p className="text-sm font-semibold">{item.appointment_time.slice(0,5)}</p><p className="mt-1 truncate text-sm">{item.patient_name}</p><span className={`mt-2 inline-flex rounded-full px-2 py-0.5 text-[10px] ${statusBadgeClass[item.appointment_status]}`}>{appointmentStatusLabels[item.appointment_status]}</span></Link>)}{!loading && dayItems.length === 0 && <p className="text-xs text-slate-400">Randevu yok</p>}</div></article>; })}</section></div>;
};
export default DoctorCalendarPage;
