import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getDoctorPatientTimeline, type PatientTimelineItem } from '../services/doctor/workspaceService';
import { appointmentStatusLabels, statusBadgeClass } from '../types/appointmentStatus';

const DoctorPatientTimelinePage = () => {
  const { patientId } = useParams(); const [items, setItems] = useState<PatientTimelineItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!patientId) return; void getDoctorPatientTimeline(patientId).then(setItems).catch((e) => { console.error(e); setError('Hasta geçmişi yüklenemedi.'); }).finally(() => setLoading(false)); }, [patientId]);
  return <div className="mx-auto max-w-4xl px-4 py-7 sm:px-6"><Link to="/doctor/patients" className="text-sm text-cyan-700 dark:text-cyan-300">← Hastalara dön</Link><h1 className="mt-4 text-3xl font-bold text-slate-950 dark:text-white">Hasta zaman çizelgesi</h1><p className="mt-2 text-sm text-slate-500">Yalnızca sizin bu hastayla olan randevu ve muayene kayıtlarınız.</p>{error && <p className="mt-5 text-rose-600">{error}</p>}<div className="mt-7 border-l-2 border-cyan-200 pl-6 dark:border-cyan-900">{items.map((item) => <article key={item.appointment_id} className="relative mb-6 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950"><span className="absolute -left-[31px] top-6 h-3 w-3 rounded-full bg-cyan-500" /><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{new Date(`${item.appointment_date}T00:00:00`).toLocaleDateString('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' })}</h2><p className="text-sm text-slate-500">{item.department} · {item.appointment_time.slice(0,5)}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs ${statusBadgeClass[item.appointment_status]}`}>{appointmentStatusLabels[item.appointment_status]}</span></div>{item.clinical_note && <div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-900"><p className="font-medium">Klinik not</p><p className="mt-2 whitespace-pre-wrap text-slate-600 dark:text-slate-300">{item.clinical_note}</p></div>}{item.follow_up_required && <div className="mt-3 text-sm text-violet-700 dark:text-violet-300"><p className="font-medium">Kontrol planı{item.follow_up_date ? ` · ${new Date(`${item.follow_up_date}T00:00:00`).toLocaleDateString('tr-TR')}` : ''}</p>{item.follow_up_note && <p className="mt-1 whitespace-pre-wrap">{item.follow_up_note}</p>}</div>}<Link to={`/doctor/appointment/${item.appointment_id}`} className="mt-4 inline-flex text-sm font-medium text-cyan-700 dark:text-cyan-300">Muayeneyi Aç →</Link></article>)}{!loading && items.length === 0 && <p className="text-slate-500">Bu hasta için erişilebilir kayıt bulunamadı.</p>}</div></div>;
};
export default DoctorPatientTimelinePage;
